# Basic imports
import numpy as np
import pandas as pd

import tqdm
import os
import glob

import datetime

# Image processing tools
import skimage.io
from skimage import (color, feature, filters, measure, morphology, segmentation, util)
import skimage.exposure
import skimage.feature
import skimage.filters
import skimage.filters.rank
from skimage.filters import threshold_otsu
import skimage.morphology
import skimage.segmentation
from skimage.segmentation import watershed
from scipy import ndimage as ndi
import scipy.signal


#################################################################################
######### Threshold #############################################################
#################################################################################


def sig_thresh_finder(histogram, bins, desired_thresh = 1000):
    ''' 
    Searches through a list of second derivatives for the bin value at which the
    previous derivative was greater than desired thresh and the current derivative is less
    than the desired thresh. If there are multiple events where this occurs, they are stored in a list and the largest one is used as a threshold. 
    '''
    
    past_i = 0
    index = 0
    thresh = []
    
    result = np.where(histogram == np.max(histogram))
    
    peak_val = bins[result[0][0]]
    
    for i in histogram:

        # Look for the threshold location
        if (past_i > desired_thresh and i <= desired_thresh) and (bins[index] > peak_val):

            # Interpolate to find the appropriate bin equal to the desired thresh
            threshold = bins[index-1] + (bins[index] - bins[index-1])*(desired_thresh - past_i)/(i-past_i)
            thresh.append(threshold)

        # Reset the parameters
        past_i = i
        index += 1
    
    if thresh != []:
        
        thresh_val = np.min(thresh)

        return(thresh_val)
    
    else:
        past_i = 0
        index = 0
        
        for i in histogram:
            # Look for the threshold location
            if (past_i > desired_thresh*0.2 and i <= desired_thresh*0.2) and (bins[index] > peak_val):

                # Interpolate to find the appropriate bin equal to the desired thresh
                threshold = bins[index-1] + (bins[index] - bins[index-1])*(desired_thresh - past_i)/(i-past_i)
                thresh.append(threshold)

            # Reset the parameters
            past_i = i
            index += 1

        if thresh != []:
            thresh_val = np.min(thresh)
            return(thresh_val)

        return(threshold_otsu(histogram))

def bf_thresh_finder(histogram, bins, desired_thresh = 10000, standard = True):
    
    past_i = 0
    index = 0
    thresh = []
    
    if standard == True:
        for i in histogram:

            # Look for the threshold location
            if past_i > desired_thresh and i <= desired_thresh:
                
                # Interpolate to find the appropriate bin equal to the desired thresh
                threshold = bins[index-1] + (bins[index] - bins[index-1])*(desired_thresh - past_i)/(i-past_i)
                thresh.append(threshold)

            # Reset the parameters
            past_i = i
            index += 1
    
        return(np.min(thresh))
        
    else: 
        # Loop through the second derivatives 
        for i in histogram:

            # Look for the threshold location
            if past_i < desired_thresh and i >= desired_thresh:

                # Interpolate to find the appropriate bin equal to the desired thresh
                threshold = bins[index-1] + (bins[index] - bins[index-1])*(desired_thresh - past_i)/(i-past_i)
                thresh.append(threshold)

            # Reset the parameters
            past_i = i
            index += 1
        
        return(np.min(thresh))


#################################################################################
######### Segementation #########################################################
#################################################################################

def brightness_counter(im_labeled, im_pos):
    '''
    Brightness counter is a function that produces a list of brightness values for up to one thousand cells in an image. 
    The brightness values is a sum of the intensity for a given labelled object.
    
    Parameters
    im_labeled: An image array with each independant object labeled with a separate value generated by skimage.measure.label
    im_pos: The result of the autofluorescence subtraction
    
    Returns
    cell_list: list of cells selected for analysis
    cell_intensities: list of cell intensities
    '''
    
    # Determine whether down-sampling is required 
    if np.max(im_labeled) > 1000:
        # Create a list of the cells to quantify the brightness in using a random number generator without replacement  
        cell_list = np.random.choice(np.arange(1, np.max(im_labeled)), 1000, replace=False)
    else:
        # If there are less than 100 cells, create a list of all the cells to access
        cell_list = np.arange(1, np.max(im_labeled) + 1)
    
    cell_intensities = {}
    
    # Simplify labels to a Nx2 array, with an array of i and an array of j indices
    nonzero_inds = im_labeled.nonzero()
    
    # Fill in an array of the cell labels for later boolean logic
    labels = im_labeled[nonzero_inds]
    
    # Instantiate dictionary
    cell_intensities = {}
 
    # Loop through the prepared cell list
    for count_value in cell_list:
        
        # Get a list of i and of j indices
        label_bool = (labels == count_value)
        inds = (nonzero_inds[0][label_bool], nonzero_inds[1][label_bool])
        
        # In the positive image, sum over the whole cell to get its intensity
        intensities = im_pos[inds]
        cell_intensity = np.sum(intensities)/len(intensities)
        
        # Append this to a list of all cell intensities
        cell_intensities[str(count_value)] = cell_intensity
        
    return(cell_list, cell_intensities)

def remove_large_objects(im, max_size = 1000, connectivity = 1):
    ''' Function to remove large objects in an image. Useful for removing large autofluorescent features.
    Parameters:
    im: a binary image array to remove the large objects from
    max_size: the maximum sized object to keep in the image
    connectivity: required pixel connectivity for contiguity
    
    Returns: 
    out: Binary image array with large ojects removed
    '''
    
    out = im.copy()
    
    selem = ndi.generate_binary_structure(im.ndim, connectivity)
    ccs = np.zeros_like(im, dtype=np.int32)
    ndi.label(im, selem, output=ccs)

    component_sizes = np.bincount(ccs.ravel())
    
    too_big = component_sizes > max_size
    too_big_mask = too_big[ccs]
    out[too_big_mask] = 0

    return(out)

def brightfield_segmentation(im_bf, gauss_sigma = 30, truncate = 0.35, dark_thresh = 10000, light_thresh = 3000, disk_radius = 2):
    # Apply a gaussian blur to determine the intensity change in the background
    im_bg = skimage.filters.gaussian(im_bf, sigma = gauss_sigma, truncate = truncate)
    
    # Subtract the background from the BF image to obtain a smoother signal with reduced background variation
    im_no_bg = im_bf - im_bg
    
    # Compute the histogram of the image intensities
    hist_bin = skimage.exposure.histogram(im_no_bg)
    hist, bins = hist_bin

    # Using the thresh_finder function, determine the threshold that enables separation of dark objects from the background by setting standard to false
    thresh_lower = bf_thresh_finder(hist, bins, desired_thresh = dark_thresh, standard = False)
    
    # Determine the dark areas
    bf_thresh = (im_no_bg < thresh_lower)
    
    # Remove large objects
    #bf_thresh = remove_large_objects(bf_thresh, max_size = 1000)
    
    # Using the thresh_finder function, determine the threshold that enables separation of bright objects from the background
    thresh_upper = bf_thresh_finder(hist, bins, desired_thresh = light_thresh, standard = True)
    
    # Combine the light areas to the dark areas
    bf_thresh += (im_no_bg > thresh_upper)
    
    # Fill in the areas of the image using a scanning disk
    binary_closed = skimage.morphology.closing(bf_thresh, 
                                               skimage.morphology.disk(radius = disk_radius))
    
    #Determine the total area of cells
    total_area = sum(sum(binary_closed))
    
    return(binary_closed, total_area)

def signal_segmentation(im_sig, gauss_sigma = 100, sig_thresh = 1000, min_size = 5):
    # Apply a gaussian blur to determine the intensity change in the background
    im_bg = skimage.filters.gaussian(im_sig, sigma = gauss_sigma)
    
    # Subtract the background from the BF image to obtain a smoother signal with reduced background variation
    im_no_bg = im_sig - im_bg
    
    # Compute the histogram of the image intensities
    hist_bin = skimage.exposure.histogram(im_no_bg)
    hist, bins = hist_bin

    # Using the thresh_finder function, determine the threshold that enables separation of bright objects from the background
    thresh = sig_thresh_finder(hist, bins, desired_thresh = sig_thresh)
    
    # Determine the dark areas
    sig_thresh = (im_no_bg > thresh)
    
    # Remove large objects
    #bf_thresh = remove_large_objects(bf_thresh, max_size = 1000)
    
    # Remove small objects
    sig_thresh = skimage.morphology.remove_small_objects(sig_thresh, min_size = min_size)
    
    #Determine the total area of cells
    total_area = sum(sum(sig_thresh))
    
    return(sig_thresh, total_area)


#################################################################################
######### Quantification ########################################################
#################################################################################



def safe_divide(numerator, denominator):
    """Return numerator / denominator, or NaN when the denominator is zero."""
    if denominator == 0 or pd.isna(denominator):
        return np.nan
    return numerator / denominator


def read_image_channel(image, channel=None):
    """
    Read an image path or normalize an existing image array.

    If channel is provided for a multi-channel image, that channel is selected.
    If channel is None, the full image is returned. This is useful for BF images
    that are already single-channel.
    """
    if isinstance(image, (str, os.PathLike)):
        image = skimage.io.imread(image)

    image = skimage.img_as_float(image)

    if channel is not None and image.ndim == 3:
        image = image[:, :, channel]

    return image


def masked_intensity(im, mask):
    """Sum image intensity inside a boolean mask."""
    return float(np.sum(im[mask]))


def masked_mean_intensity(im, mask):
    """Mean image intensity inside a boolean mask."""
    area = int(np.sum(mask))
    return safe_divide(masked_intensity(im, mask), area)


def quantify_signal_mask(im_signal, signal_mask):
    """Return area, mean intensity, and total masked intensity for one signal image."""
    signal_area = int(np.sum(signal_mask))
    signal_intensity_sum = masked_intensity(im_signal, signal_mask)

    return {
        'area': signal_area,
        'intensity': safe_divide(signal_intensity_sum, signal_area),
        'intensity_sum': signal_intensity_sum,
    }


def quantify_overlap(receptor_mask, signal_mask, signal_image):
    """
    Quantify overlap between a reference mask and a query mask.

    For the current RG assay, reference is usually R and query is usually G.
    """
    overlap_mask = receptor_mask & signal_mask

    receptor_area = int(np.sum(receptor_mask))
    signal_area = int(np.sum(signal_mask))
    overlapping_area = int(np.sum(overlap_mask))
    signal_intensity_all_sum = masked_intensity(signal_image, signal_mask)
    signal_intensity_overlapping_sum = masked_intensity(signal_image, overlap_mask)
    signal_intensity_all = safe_divide(signal_intensity_all_sum, signal_area)
    signal_intensity_overlapping = safe_divide(
        signal_intensity_overlapping_sum,
        overlapping_area,
    )
    union_area = int(np.sum(receptor_mask | signal_mask))

    return {
        'receptor_area': receptor_area,
        'signal_area': signal_area,
        'overlapping_area': overlapping_area,
        'signal_intensity_all': signal_intensity_all,
        'signal_intensity_overlapping': signal_intensity_overlapping,
        'signal_intensity_all_sum': signal_intensity_all_sum,
        'signal_intensity_overlapping_sum': signal_intensity_overlapping_sum,
        'signal_in_receptor_fraction': safe_divide(overlapping_area, receptor_area),
        'receptor_in_signal_fraction': safe_divide(overlapping_area, signal_area),
        'overlap_over_union_fraction': safe_divide(overlapping_area, union_area),
        'signal_intensity_overlap_fraction': safe_divide(
            signal_intensity_overlapping_sum,
            signal_intensity_all_sum,
        ),
        'overlap_mask': overlap_mask,
    }


def quantify_cell_brightness_stats(
        im_signal,
        signal_mask,
        h_max=0.01,
        include_percentiles=False,
        collected_percentiles=(5, 95),
        ):
    """
    Optional watershed-based cell/object brightness stats.

    This is off by default in the new RG overlap workflow because area and
    overlap intensity do not require splitting the mask into cell-like objects.
    """
    image_max = skimage.morphology.h_maxima(im_signal, h_max)
    maxima = skimage.measure.label(image_max)
    labels = watershed(signal_mask, maxima, mask=signal_mask)
    im_labeled, n_labels = skimage.measure.label(labels, background=0, return_num=True)

    cell_list, cell_intensity_list = brightness_counter(im_labeled, im_signal)
    intensities = list(cell_intensity_list.values())

    result = {
        'cell_count': int(n_labels),
        'cells_quantified': cell_list,
        'cell_brightness': cell_intensity_list,
        'median_cell_brightness': np.median(intensities) if intensities else np.nan,
    }

    if include_percentiles and intensities:
        low, high = collected_percentiles
        result[f'cell_brightness_p{low}'] = np.percentile(intensities, low)
        result[f'cell_brightness_p{high}'] = np.percentile(intensities, high)

    return result


def quantify_bf_rg_overlap(
        im_bf,
        im_r,
        im_g,
        bf_params=None,
        r_signal_params=None,
        g_signal_params=None,
        min_r_area=0,
        min_r_area_fraction=None,
        min_r_intensity=None,
        min_r_intensity_sum=None,
        include_cell_stats=False,
        include_percentiles=False,
        collected_percentiles=(5, 95),
        h_max=0.01,
        include_masks=False,
        ):
    """
    Quantify BF/R/G area, overlap area, and G intensity.

    Core outputs:
    - bf_area
    - r_area
    - r_intensity
    - r_filter
    - g_area
    - overlapping_area
    - overlap_r
    - overlap_g
    - g_intensity_all
    - g_intensity_overlap
    """
    bf_params = bf_params or {}
    r_signal_params = r_signal_params or {}
    g_signal_params = g_signal_params or {}

    bf_mask, bf_area = brightfield_segmentation(im_bf, **bf_params)
    r_mask, r_area = signal_segmentation(im_r, **r_signal_params)
    g_mask, g_area = signal_segmentation(im_g, **g_signal_params)

    r_area_raw = int(r_area)
    r_area_fraction_raw = safe_divide(r_area_raw, bf_area)
    r_quant_raw = quantify_signal_mask(im_r, r_mask)
    r_intensity_raw = r_quant_raw['intensity']
    r_intensity_sum_raw = r_quant_raw['intensity_sum']
    r_area_filtered = (
        (min_r_area is not None and r_area_raw < min_r_area)
        or (
            min_r_area_fraction is not None
            and r_area_fraction_raw < min_r_area_fraction
        )
    )
    if r_area_filtered:
        r_mask = np.zeros_like(r_mask, dtype=bool)
        r_area = 0

    r_intensity_filtered = (
        (
            min_r_intensity is not None
            and (
                pd.isna(r_intensity_raw)
                or r_intensity_raw < min_r_intensity
            )
        )
        or (
            min_r_intensity_sum is not None
            and r_intensity_sum_raw < min_r_intensity_sum
        )
    )
    if r_intensity_filtered:
        r_mask = np.zeros_like(r_mask, dtype=bool)
        r_area = 0

    overlap_result = quantify_overlap(r_mask, g_mask, im_g)

    result = {
        'bf_area': int(bf_area),
        'r_area': int(r_area),
        'r_intensity': r_intensity_raw,
        'r_filter': r_area_filtered or r_intensity_filtered,
        'g_area': int(g_area),
        'overlapping_area': overlap_result['overlapping_area'],
        'overlap_r': overlap_result['signal_in_receptor_fraction'],
        'overlap_g': overlap_result['receptor_in_signal_fraction'],
        'g_intensity_all': overlap_result['signal_intensity_all'],
        'g_intensity_overlap': overlap_result['signal_intensity_overlapping'],
    }

    if include_cell_stats:
        result.update(
            quantify_cell_brightness_stats(
                im_g,
                g_mask,
                h_max=h_max,
                include_percentiles=include_percentiles,
                collected_percentiles=collected_percentiles,
            )
        )

    if include_masks:
        result.update({
            'bf_mask': bf_mask,
            'r_mask': r_mask,
            'g_mask': g_mask,
            'overlap_mask': overlap_result['overlap_mask'],
        })

    return result


def assay_rg_overlap_analysis(
        df_metadata,
        image_directory,
        output_file=None,
        bf_label='bf',
        r_label='r',
        g_label='g',
        r_channel=0,
        g_channel=1,
        bf_channel=None,
        bf_params=None,
        r_signal_params=None,
        g_signal_params=None,
        min_r_area=0,
        min_r_area_fraction=None,
        min_r_intensity=None,
        min_r_intensity_sum=None,
        include_cell_stats=False,
        include_percentiles=False,
        collected_percentiles=(5, 95),
        ):
    """
    New batch analysis for the BF/R/G overlap workflow.

    Returns one row per experiment with the core requested outputs plus useful
    percentage columns and processing status.
    """
    df_metadata = df_metadata.copy()
    if 'include' in df_metadata.columns:
        df_metadata = df_metadata[df_metadata['include'] == 1].copy()

    results = []

    for exp_id in tqdm.tqdm(df_metadata['experiment_id'].unique(), desc="Processing RG overlap"):
        exp_data = df_metadata[df_metadata['experiment_id'] == exp_id]

        base = {'experiment_id': exp_id, 'status': 'ok', 'error': ''}
        metadata_cols = [
            col for col in exp_data.columns
            if col not in ['figure_name', 'figure_id', 'channel', 'include', 'notes']
        ]
        for col in metadata_cols:
            base[col] = exp_data.iloc[0][col]

        bf_rows = exp_data[exp_data['channel'] == bf_label]
        r_rows = exp_data[exp_data['channel'] == r_label]
        g_rows = exp_data[exp_data['channel'] == g_label]

        if len(bf_rows) == 0 or len(r_rows) == 0 or len(g_rows) == 0:
            base.update({
                'status': 'skipped',
                'error': f"Missing required channel: {bf_label}, {r_label}, or {g_label}",
            })
            results.append(base)
            continue

        bf_path = os.path.join(image_directory, bf_rows.iloc[0]['figure_name'])
        r_path = os.path.join(image_directory, r_rows.iloc[0]['figure_name'])
        g_path = os.path.join(image_directory, g_rows.iloc[0]['figure_name'])

        base.update({
            'bf_file': bf_rows.iloc[0]['figure_name'],
            'r_file': r_rows.iloc[0]['figure_name'],
            'g_file': g_rows.iloc[0]['figure_name'],
        })

        missing_files = [
            path for path in [bf_path, r_path, g_path]
            if not os.path.exists(path)
        ]
        if missing_files:
            base.update({
                'status': 'skipped',
                'error': f"Missing image file(s): {missing_files}",
            })
            results.append(base)
            continue

        try:
            im_bf = read_image_channel(bf_path, channel=bf_channel)
            im_r = read_image_channel(r_path, channel=r_channel)
            im_g = read_image_channel(g_path, channel=g_channel)

            quant_result = quantify_bf_rg_overlap(
                im_bf,
                im_r,
                im_g,
                bf_params=bf_params,
                r_signal_params=r_signal_params,
                g_signal_params=g_signal_params,
                min_r_area=min_r_area,
                min_r_area_fraction=min_r_area_fraction,
                min_r_intensity=min_r_intensity,
                min_r_intensity_sum=min_r_intensity_sum,
                include_cell_stats=include_cell_stats,
                include_percentiles=include_percentiles,
                collected_percentiles=collected_percentiles,
                include_masks=False,
            )
            base.update(quant_result)

        except Exception as e:
            base.update({'status': 'error', 'error': str(e)})

        results.append(base)

    df_results = pd.DataFrame(results)

    if output_file is not None:
        df_results.to_csv(output_file, index=False)

    return df_results
